runtime: nodejs
env: flex

endpoints_api_service:
  name: cs3219-peerprep-330604.as.r.appspot.com
  rollout_strategy: managed

resources:
  cpu: 1
  memory_gb: 6
  disk_size_gb: 20

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1800