name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
      - branch_ch_GCP_deployment
jobs:
  build:
    name: GAE Deploy
    working-directory: ./api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}