name: Deploy to Google App Engine
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./api

jobs:
  deployGAE:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: google-github-actions/deploy-appengine@main
          with:
            working_directory: ./api
            deliverables: ./app.yaml
            credentials: ${{ secrets.gcp_credentials }}