name: Deploy Frontend to Google App Engine
on:
  push:
    branches:
      - main
      - philip/deploy_frontend
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
        working-directory: ./client
      - name: Build
        env:
          CI: false
        run: npm run-script build
        working-directory: ./client
  deployGAE:
    name: deploy frontend on GAE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          working_directory: ./client
          deliverables: ./app.yaml
          credentials: ${{ secrets.GCP_CREDENTIALS_FRONTEND }}
