# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy to Firebase

on:
  push:
    branches: 
      - main
      - philip/firebase_deploy
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      - name: Install dependencies
        run: npm install
        working-directory: ./client
      - name: Build
        env:
          CI: false
        run: npm run-script build
        working-directory: ./client
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          projectId: cs3219-peerprep-frontend
          entryPoint: ./client
          channelId: live